### PR TITLE
Fix test_continuationtoken_empty

### PR DESCRIPTION
**Pull request by masterSplinter01**
Now this test processes an error in a response.

### CODE REVIEW

**Review by KirillovDenis — APPROVED** [review]

**Comment by realloc** [comment]
I suggest moving the fixed on to our own suite

**Comment by masterSplinter01** [comment]
But this PR is already a request to merge the fix to master branch of our fork.

**Comment by alexvanin** [comment]
> > I suggest moving the fixed on to our own suite
>
> But this PR is already a request to merge the fix to master branch of our fork.

I think @realloc meant not to change existing `test_bucket_listv2_continuationtoken_empty` test, but to create one more `test_bucket_listv2_continuationtoken_empty_fixed` (choose better naming) test with fixed behavior.

This branch, however, can be used for upstream PR. But first let's run compatibility tests against S3: https://github.com/nspcc-dev/neofs-s3-gw/issues/183. It will help to prove that our PR is valid.

**Comment by KirillovDenis** [comment]
We also can add some attribute (like this one `@attr('fixed_to_neofs_s3_gate')`) to be able to run such tests separately.

**Comment by masterSplinter01** [comment]
Will add docs to confluence how to run tests with our attribute (`fixed_to_neofs_s3_gw` looks good enough for name of our suite?) after approve/merge.

**Review by alexvanin — APPROVED** [review]

**Pull request merged**
